[theme]
base = "light"
primaryColor = "#58CC02"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#3C3C3C"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
